"""Built-in ROI segmentation hook for Femtonics TIFF images."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
from PIL import Image

try:
    from .roi_core import (
        RoiBox,
        compute_roi_layout,
        load_tiff_info,
        metadata_path_for_tiff,
        parse_metadata,
        save_tiff_array_stack,
        validate_tiff_matches_metadata,
    )
    from .summary_images import (
        auto_display_range,
        compute_summary_images,
        scale_to_uint8,
        upscale_export_image,
        write_summary_outputs,
    )
    from .tiff_backend import iter_tiff_frames
except ImportError:  # pragma: no cover - supports direct script-style imports.
    from roi_core import (
        RoiBox,
        compute_roi_layout,
        load_tiff_info,
        metadata_path_for_tiff,
        parse_metadata,
        save_tiff_array_stack,
        validate_tiff_matches_metadata,
    )
    from summary_images import (
        auto_display_range,
        compute_summary_images,
        scale_to_uint8,
        upscale_export_image,
        write_summary_outputs,
    )
    from tiff_backend import iter_tiff_frames


def _default_output_dir(tiff_path: Path, output_dir: Path | None) -> Path:
    if output_dir is not None:
        return Path(output_dir)
    return tiff_path.parent / "exports" / tiff_path.stem


def _whole_frame_box(frame_shape: tuple[int, int]) -> RoiBox:
    height, width = frame_shape
    return RoiBox(
        ordinal=1,
        roi_index=1,
        row=0,
        column=0,
        left=0,
        upper=0,
        right=width,
        lower=height,
    )


def _layout_boxes_for_tiff(tiff_path: Path, frame_shape: tuple[int, int]) -> tuple[list[RoiBox], Path | None, str]:
    metadata_path = metadata_path_for_tiff(tiff_path)
    if metadata_path.exists():
        metadata = parse_metadata(metadata_path)
        info = load_tiff_info(tiff_path)
        validate_tiff_matches_metadata(info, metadata)
        return compute_roi_layout(metadata).boxes, metadata_path, "metadata_tiles"
    return [_whole_frame_box(frame_shape)], None, "whole_frame"


def _write_full_frame_metadata(path: Path, *, width: int, height: int, dtype_name: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""%Metadata generated by image_processor.segmentation_hooks
Type: GeneratedFullFrame

>Context start
%SIZE
 Width: {width}
 Height: {height}
%PATTERN
 PatternNum: 1
 RoiCount: 1
 RoiSize (pixels): [[{width}, {height}]]
 RoiIndex: [1]
 DataType: {dtype_name}
<Context end
""",
        encoding="utf-8",
    )


def build_mean_image(tiff_path: Path) -> tuple[np.ndarray, int, str]:
    """Return a float32 mean projection for a 2D TIFF image or stack."""
    accumulator: np.ndarray | None = None
    frame_count = 0
    dtype_name = ""

    for frame_index, frame in enumerate(iter_tiff_frames(tiff_path)):
        array = np.asarray(frame)
        if array.ndim != 2:
            raise ValueError(f"ROI segmentation expects grayscale 2D frames, got shape {array.shape}.")
        if accumulator is None:
            accumulator = np.zeros(array.shape, dtype=np.float64)
            dtype_name = str(array.dtype)
        elif array.shape != accumulator.shape:
            raise ValueError(f"Frame {frame_index} shape {array.shape} does not match first frame {accumulator.shape}.")
        accumulator += array.astype(np.float64, copy=False)
        frame_count += 1

    if accumulator is None or frame_count == 0:
        raise ValueError(f"TIFF contains no frames: {tiff_path}")
    return (accumulator / float(frame_count)).astype(np.float32), frame_count, dtype_name


def threshold_tile(
    tile: np.ndarray,
    *,
    percentile: float = 95.0,
    std_factor: float = 2.5,
    method: str = "foreground",
    foreground_percentile: float = 60.0,
) -> tuple[np.ndarray, float]:
    values = np.asarray(tile, dtype=np.float32)
    finite = values[np.isfinite(values)]
    if finite.size == 0:
        return np.zeros(values.shape, dtype=bool), 0.0

    observed_min = float(np.min(finite))
    observed_max = float(np.max(finite))
    if observed_max <= observed_min:
        return np.zeros(values.shape, dtype=bool), observed_max

    normalized_method = str(method or "foreground").strip().lower()
    if normalized_method in {"foreground", "shape", "adaptive", "auto"}:
        threshold = float(np.percentile(finite, float(foreground_percentile)))
        if threshold >= observed_max:
            threshold = max(observed_min, np.nextafter(observed_max, observed_min))
        return values > threshold, threshold
    if normalized_method == "otsu":
        threshold = otsu_threshold(finite)
        return values > threshold, threshold
    if normalized_method not in {"brightest", "percentile", "legacy"}:
        raise ValueError(
            "Unknown segmentation threshold_method "
            f"{method!r}; expected 'foreground', 'otsu', or 'brightest'."
        )

    median = float(np.median(finite))
    mad = float(np.median(np.abs(finite - median)))
    robust_sigma = 1.4826 * mad
    mean = float(np.mean(finite))
    std = float(np.std(finite))
    percentile_value = float(np.percentile(finite, float(percentile)))

    robust_threshold = median + float(std_factor) * robust_sigma
    standard_threshold = mean + float(std_factor) * std
    threshold = max(percentile_value, min(robust_threshold, standard_threshold))
    if threshold >= observed_max:
        threshold = max(observed_min, np.nextafter(observed_max, observed_min))
    return values > threshold, threshold


def otsu_threshold(values: np.ndarray) -> float:
    finite = np.asarray(values, dtype=np.float32)
    finite = finite[np.isfinite(finite)]
    if finite.size == 0:
        return 0.0

    observed_min = float(np.min(finite))
    observed_max = float(np.max(finite))
    if observed_max <= observed_min:
        return observed_max

    bin_count = min(128, max(8, int(np.sqrt(finite.size)) * 4))
    hist, edges = np.histogram(finite, bins=bin_count)
    if not np.any(hist):
        return observed_max

    centers = (edges[:-1] + edges[1:]) * 0.5
    total = float(hist.sum())
    background_weight = np.cumsum(hist).astype(np.float64)
    foreground_weight = total - background_weight

    background_mean = np.cumsum(hist * centers) / np.maximum(background_weight, 1.0)
    reverse_weight = np.cumsum(hist[::-1]).astype(np.float64)
    reverse_mean = np.cumsum((hist * centers)[::-1]) / np.maximum(reverse_weight, 1.0)
    foreground_mean = reverse_mean[::-1]

    if centers.size < 2:
        return float(centers[0])

    score = (
        background_weight[:-1]
        * foreground_weight[:-1]
        * (background_mean[:-1] - foreground_mean[1:]) ** 2
    )
    if score.size == 0 or not np.any(np.isfinite(score)):
        return float((observed_min + observed_max) * 0.5)
    return float(centers[int(np.nanargmax(score))])


def _component_records(
    mask: np.ndarray,
    *,
    min_area: int,
    max_area: int | None,
) -> list[dict[str, Any]]:
    binary = np.asarray(mask, dtype=bool)
    height, width = binary.shape
    visited = np.zeros(binary.shape, dtype=bool)
    components: list[dict[str, Any]] = []

    for start_y, start_x in np.argwhere(binary):
        sy = int(start_y)
        sx = int(start_x)
        if visited[sy, sx]:
            continue

        stack = [(sy, sx)]
        visited[sy, sx] = True
        ys: list[int] = []
        xs: list[int] = []

        while stack:
            y, x = stack.pop()
            ys.append(y)
            xs.append(x)
            for ny in range(max(0, y - 1), min(height, y + 2)):
                for nx in range(max(0, x - 1), min(width, x + 2)):
                    if visited[ny, nx] or not binary[ny, nx]:
                        continue
                    visited[ny, nx] = True
                    stack.append((ny, nx))

        area = len(ys)
        if area < min_area:
            continue
        if max_area is not None and area > max_area:
            continue

        ys_array = np.asarray(ys, dtype=np.int32)
        xs_array = np.asarray(xs, dtype=np.int32)
        components.append(
            {
                "area": int(area),
                "ys": ys_array,
                "xs": xs_array,
                "bbox": (
                    int(np.min(xs_array)),
                    int(np.min(ys_array)),
                    int(np.max(xs_array)) + 1,
                    int(np.max(ys_array)) + 1,
                ),
                "centroid": (
                    float(np.mean(xs_array)),
                    float(np.mean(ys_array)),
                ),
            }
        )

    return components


def detect_tile_components(
    mean_image: np.ndarray,
    boxes: list[RoiBox],
    *,
    min_area: int = 4,
    percentile: float = 95.0,
    foreground_percentile: float = 60.0,
    std_factor: float = 2.5,
    max_area_fraction: float = 0.6,
    threshold_method: str = "foreground",
) -> tuple[np.ndarray, list[dict[str, Any]]]:
    height, width = mean_image.shape
    label_image = np.zeros((height, width), dtype=np.uint32)
    detections: list[dict[str, Any]] = []
    next_label = 1

    for box in boxes:
        tile = np.asarray(mean_image[box.upper : box.lower, box.left : box.right])
        tile_area = int(tile.shape[0] * tile.shape[1])
        max_area = int(tile_area * float(max_area_fraction)) if max_area_fraction > 0 else None
        binary, threshold = threshold_tile(
            tile,
            percentile=percentile,
            foreground_percentile=foreground_percentile,
            std_factor=std_factor,
            method=threshold_method,
        )

        for component_number, component in enumerate(
            _component_records(binary, min_area=int(min_area), max_area=max_area),
            start=1,
        ):
            local_ys = component["ys"]
            local_xs = component["xs"]
            global_ys = local_ys + box.upper
            global_xs = local_xs + box.left
            label_image[global_ys, global_xs] = next_label

            left, upper, right, lower = component["bbox"]
            centroid_x, centroid_y = component["centroid"]
            label = f"ROI{box.roi_index:02d}_S{component_number:02d}"
            detections.append(
                {
                    "label": label,
                    "label_id": int(next_label),
                    "parent_roi_index": int(box.roi_index),
                    "parent_ordinal": int(box.ordinal),
                    "area_px": int(component["area"]),
                    "threshold": float(threshold),
                    "threshold_method": str(threshold_method),
                    "foreground_percentile": float(foreground_percentile),
                    "bbox_local": {
                        "left": int(left),
                        "upper": int(upper),
                        "right": int(right),
                        "lower": int(lower),
                    },
                    "bbox_global": {
                        "left": int(box.left + left),
                        "upper": int(box.upper + upper),
                        "right": int(box.left + right),
                        "lower": int(box.upper + lower),
                    },
                    "centroid_local": {
                        "x": float(centroid_x),
                        "y": float(centroid_y),
                    },
                    "centroid_global": {
                        "x": float(box.left + centroid_x),
                        "y": float(box.upper + centroid_y),
                    },
                }
            )
            next_label += 1

    return label_image, detections


def _masks_from_label_image(label_image: np.ndarray, detections: list[dict[str, Any]]) -> np.ndarray:
    if not detections:
        return np.zeros((0, *label_image.shape), dtype=bool)
    masks = np.zeros((len(detections), *label_image.shape), dtype=bool)
    for index, detection in enumerate(detections):
        masks[index] = label_image == int(detection["label_id"])
    return masks


def _tile_manifest_records(boxes: list[RoiBox], detections: list[dict[str, Any]]) -> list[dict[str, Any]]:
    counts_by_parent: dict[int, int] = {}
    for detection in detections:
        parent = int(detection["parent_roi_index"])
        counts_by_parent[parent] = counts_by_parent.get(parent, 0) + 1

    return [
        {
            "roi_index": int(box.roi_index),
            "ordinal": int(box.ordinal),
            "row": int(box.row),
            "column": int(box.column),
            "bbox_global": {
                "left": int(box.left),
                "upper": int(box.upper),
                "right": int(box.right),
                "lower": int(box.lower),
            },
            "detected_roi_count": counts_by_parent.get(int(box.roi_index), 0),
        }
        for box in boxes
    ]


def mask_boundary(mask: np.ndarray) -> np.ndarray:
    binary = np.asarray(mask, dtype=bool)
    if binary.size == 0:
        return np.zeros(binary.shape, dtype=bool)
    padded = np.pad(binary, 1, mode="constant", constant_values=False)
    neighbors_all_inside = np.ones(binary.shape, dtype=bool)
    for dy in range(3):
        for dx in range(3):
            neighbors_all_inside &= padded[dy : dy + binary.shape[0], dx : dx + binary.shape[1]]
    return binary & ~neighbors_all_inside


def save_segmentation_overlay_png(
    mean_image: np.ndarray,
    label_image: np.ndarray,
    boxes: list[RoiBox],
    detections: list[dict[str, Any]],
    output_path: Path,
) -> Path:
    """Write a quick-look PNG with detected masks over the mean projection."""
    black_level, white_level = auto_display_range(mean_image)
    base = scale_to_uint8(mean_image, black_level, white_level)
    rgb = np.repeat(base[:, :, np.newaxis], 3, axis=2).astype(np.float32)
    palette = np.asarray(
        [
            (255, 80, 80),
            (80, 220, 120),
            (80, 160, 255),
            (255, 210, 80),
            (210, 100, 255),
            (80, 230, 230),
            (255, 145, 80),
            (180, 255, 90),
        ],
        dtype=np.float32,
    )

    for detection in detections:
        label_id = int(detection["label_id"])
        mask = label_image == label_id
        if not np.any(mask):
            continue
        color = palette[(label_id - 1) % len(palette)]
        boundary = mask_boundary(mask)
        rgb[mask] = rgb[mask] * 0.82 + color * 0.18
        rgb[boundary] = rgb[boundary] * 0.15 + color * 0.85

    output_path.parent.mkdir(parents=True, exist_ok=True)
    image = Image.fromarray(np.clip(np.rint(rgb), 0, 255).astype(np.uint8), mode="RGB")
    upscale_export_image(image).save(output_path)
    return output_path


def write_segmentation_outputs(
    *,
    tiff_path: Path,
    output_dir: Path,
    mean_image: np.ndarray,
    frame_count: int,
    dtype_name: str,
    boxes: list[RoiBox],
    layout_source: str,
    metadata_path: Path | None,
    min_area: int,
    percentile: float,
    foreground_percentile: float,
    std_factor: float,
    max_area_fraction: float,
    threshold_method: str,
    summary_paths: dict[str, Path] | None = None,
) -> dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)
    label_image, detections = detect_tile_components(
        mean_image,
        boxes,
        min_area=min_area,
        percentile=percentile,
        foreground_percentile=foreground_percentile,
        std_factor=std_factor,
        max_area_fraction=max_area_fraction,
        threshold_method=threshold_method,
    )

    if metadata_path is None:
        metadata_path = output_dir / f"{tiff_path.stem}.metadata.txt"
        _write_full_frame_metadata(
            metadata_path,
            width=int(mean_image.shape[1]),
            height=int(mean_image.shape[0]),
            dtype_name=dtype_name,
        )

    mask_path = output_dir / f"{tiff_path.stem}_segmentation_masks.npz"
    labels = np.asarray([detection["label"] for detection in detections], dtype=str)
    np.savez_compressed(
        mask_path,
        masks=_masks_from_label_image(label_image, detections),
        label_image=label_image,
        labels=labels,
    )

    label_tiff_path = output_dir / f"{tiff_path.stem}_segmentation_labels.tiff"
    label_dtype = np.uint16 if len(detections) <= np.iinfo(np.uint16).max else np.uint32
    save_tiff_array_stack(label_tiff_path, label_image.astype(label_dtype, copy=False)[np.newaxis, :, :])

    overlay_path = save_segmentation_overlay_png(
        mean_image,
        label_image,
        boxes,
        detections,
        output_dir / f"{tiff_path.stem}_segmentation_overlay.png",
    )

    manifest_path = output_dir / f"{tiff_path.stem}_segmentation_manifest.json"
    manifest = {
        "ok": True,
        "source_tiff": str(tiff_path),
        "metadata_path": str(metadata_path),
        "frame_count": int(frame_count),
        "mean_image_shape": [int(mean_image.shape[0]), int(mean_image.shape[1])],
        "layout_source": layout_source,
        "tile_count": len(boxes),
        "tiles": _tile_manifest_records(boxes, detections),
        "summary_outputs": {key: str(path) for key, path in (summary_paths or {}).items()},
        "qc_overlay_png": str(overlay_path),
        "parameters": {
            "min_area": int(min_area),
            "percentile": float(percentile),
            "foreground_percentile": float(foreground_percentile),
            "std_factor": float(std_factor),
            "max_area_fraction": float(max_area_fraction),
            "threshold_method": str(threshold_method),
        },
        "detected_roi_count": len(detections),
        "detections": detections,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    result = {
        "ok": True,
        "metadata_path": str(metadata_path),
        "detected_roi_count": len(detections),
        "mask_path": str(mask_path),
        "label_tiff": str(label_tiff_path),
        "qc_overlay_png": str(overlay_path),
        "mask_manifest_path": str(manifest_path),
        "layout_source": layout_source,
        "tile_count": len(boxes),
        "frame_count": int(frame_count),
    }
    if summary_paths:
        result.update({key: str(path) for key, path in summary_paths.items()})
        result["summary_paths"] = [str(path) for path in summary_paths.values()]
    return result


def roi_hook(
    tiff_path: Path,
    output_dir: Path | None = None,
    **kwargs: Any,
) -> dict[str, Any]:
    source = Path(tiff_path)
    target_dir = _default_output_dir(source, Path(output_dir) if output_dir is not None else None)
    summary = compute_summary_images(source)
    summary_paths = write_summary_outputs(summary, target_dir, tiff_stem=source.stem)
    boxes, metadata_path, layout_source = _layout_boxes_for_tiff(source, summary.mean.shape)

    return write_segmentation_outputs(
        tiff_path=source,
        output_dir=target_dir,
        mean_image=summary.mean,
        frame_count=summary.frame_count,
        dtype_name=summary.source_dtype,
        boxes=boxes,
        layout_source=layout_source,
        metadata_path=metadata_path,
        min_area=int(kwargs.get("min_area", 4)),
        percentile=float(kwargs.get("percentile", 95.0)),
        foreground_percentile=float(kwargs.get("foreground_percentile", 60.0)),
        std_factor=float(kwargs.get("std_factor", 2.5)),
        max_area_fraction=float(kwargs.get("max_area_fraction", 0.6)),
        threshold_method=str(kwargs.get("threshold_method", "foreground")),
        summary_paths=summary_paths,
    )


run = roi_hook
